@baseURL = http://localhost:8000
@token = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zOUFabVhKWXFuMVQxb0dPaXRqVzl1M2l4M1kiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE4MDE3NTMwNzQsImlhdCI6MTc3MDIxNzA3NCwiaXNzIjoiaHR0cHM6Ly9zcGxlbmRpZC10b3VjYW4tMTcuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiMTE4Y2Q2NmQ2ODQxZmE0NTBlN2IiLCJuYmYiOjE3NzAyMTcwNjksInN1YiI6InVzZXJfMzlBZzh5djFDQ0tlZFJkOHRrY1lqeTZJaERuIn0.CzhTdh7sjHkX_pWufsx37sFkIbAs_4gSIXX1ON-FI9mpVSs6Um6eWN5OQrYpl9SJFOxoYhU5hSfgRCGOzupCdac6kCw5O-bJ9KajGsDoFGlovOQ2p-Is2wFKZpC2a-vZAMeyVPB7ItDSzNCCJEh9duU7mk7onySARWxmoNjVWTEJcnaMcVYLb8IpByqmCBSUgEjkJD-lyoBZ3Phb_C3wyM5OIg0XEL05mLhi4Ztm7lR6c6i-kF8YsaZbYswDKYQs5SQsoxExdU_8RrmT2WGk9HE15ttDoSZFDW3pbFaQLP3TioVE4gshbEMLzqpfjHnRiS7BPlVled8UjCHwo0aK-w
@userId = user_39Ag8yv1CCKedRd8tkcYjy6IhDn


# =====================
# Project E2E Tests
# =====================

### Test: Get all items
GET {{baseURL}}/v1/projects/
Accept: application/json
Authorization: Bearer {{token}}

